apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-publisher-config
data:
  # basic config options.
  #config.organization: kubernetes
  config.organization: caesarxuchao
  config.project: kubernetes
  config.pr-mungers: publisher
  config.token-file: /etc/secret-volume/token

  # munger specific options.
  config.period: "24h"
